sudo: false
dist: focal
language: python
install: pip install tox
script: tox

matrix:
  include:
    - python: 2.7
      env: TOXENV=py27
    - python: 3.5
      env: TOXENV=py35
    - python: 3.6
      env: TOXENV=py36
    - python: 3.7
      env: TOXENV=py37
    - python: 3.8
      env: TOXENV=py38
    - python: 3.9
      env: TOXENV=py39
    - python: 3.10
      env: TOXENV=py310
    - python: 3.11
      env: TOXENV=py311
    - python: pypy2.7-7.3.1
      env: TOXENV=pypy2
    - python: pypy3.6-7.3.1
      env: TOXENV=pypy3
